# Generated by Django 2.1.1 on 2018-11-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('point_value', models.IntegerField(verbose_name='point value')),
                ('rep_standard', models.IntegerField(blank=True, null=True, verbose_name='rep standard')),
                ('time_limit_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time_limit_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time_limit_miliseconds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance_standard_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance_standard_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('event_time', models.DateTimeField(verbose_name='event time')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
