# Generated by Django 2.1.1 on 2018-11-15 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181114_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
