# Generated by Django 2.1.1 on 2018-11-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181116_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventInfo',
            new_name='Venue',
        ),
    ]
