# Generated by Django 2.1.1 on 2018-11-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181116_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
