# Generated by Django 2.1.1 on 2018-11-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='event',
        ),
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ManyToManyField(to='events.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
