# Generated by Django 2.1.1 on 2018-11-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20181117_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-day_1_date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='day_1_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='day_1_location',
            field=models.CharField(default='Statesville High School', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='day_1_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='day_2_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='day_2_location',
            field=models.CharField(default='Mac Anderson Park', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='day_2_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
