# Generated by Django 2.1.1 on 2018-11-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181119_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('time', models.TimeField(default=None, null=True)),
                ('location', models.CharField(default='Statesville High School', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_1_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_1_location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_1_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_2_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_2_location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_2_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
