# Generated by Django 2.1.1 on 2018-11-19 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20181119_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
