# Generated by Django 2.1.1 on 2018-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_day_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
