# Generated by Django 2.1.1 on 2018-11-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20181119_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Day'),
        ),
    ]
