# Generated by Django 2.1.1 on 2018-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20181119_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='activity',
            field=models.ManyToManyField(to='events.Activity'),
        ),
        migrations.AlterField(
            model_name='day',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
