# Generated by Django 2.1.1 on 2018-11-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20181119_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Day'),
        ),
    ]
