# Generated by Django 2.1.1 on 2018-11-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20181119_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RepStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RepStdHard', models.IntegerField()),
                ('RepStdWarrior', models.IntegerField()),
                ('RepStdElite', models.IntegerField()),
                ('activity_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.ActivityInstance')),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='distance_standard_meters',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='distance_standard_miles',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='point_value',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='rep_standard',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time_limit_miliseconds',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time_limit_minutes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time_limit_seconds',
        ),
        migrations.RemoveField(
            model_name='day',
            name='burpee',
        ),
        migrations.DeleteModel(
            name='Burpee',
        ),
        migrations.AddField(
            model_name='activityinstance',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Activity'),
        ),
    ]
