# Generated by Django 2.1.1 on 2018-11-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_all', models.DecimalField(decimal_places=3, max_digits=10)),
                ('units_all', models.CharField(choices=[('MINUTES', 'minutes'), ('SECONDS', 'seconds'), ('MILISECONDS', 'miliseconds')], max_length=10)),
                ('time_limit_hard', models.DecimalField(decimal_places=3, max_digits=10)),
                ('time_limit_warrior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('time_limit_elite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('activity_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.ActivityInstance')),
            ],
        ),
    ]
