# Generated by Django 2.1.1 on 2018-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_timelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelimit',
            name='time_limit_all',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='time_limit_elite',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='time_limit_hard',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='time_limit_warrior',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='units_all',
            field=models.CharField(blank=True, choices=[('MINUTES', 'minutes'), ('SECONDS', 'seconds'), ('MILISECONDS', 'miliseconds')], max_length=10, null=True),
        ),
    ]
